FROM python:3.9-slim

RUN mkdir /api

WORKDIR /api

COPY reqs.txt .

RUN pip install -r reqs.txt

COPY . .

CMD ["gunicorn", "app.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8000"]